import type { Metadata } from "next";
import { Geist, Geist_Mono, Urbanist } from "next/font/google";
import "./globals.css";
import ThemeToggle from "./_components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen min-h-screen max-h-screen flex-col bg-zinc-50 font-sans dark:bg-black">
          <div className="flex px-8 py-4 border-b dark:border-zinc-700 shadow bg-zinc-50 dark:bg-zinc-900 items-center justify-between">
            <div className="text-2xl font-bold">Borders Varients</div>
            <ThemeToggle />
          </div>
          <div className="flex h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
